language: phyton

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - pip install oletools
  - pip install pymilter
  - pip install configparser


  before_script:
  - sudo service postfix stop
  - sudo postconf -e smtpd_milters=inet:127.0.0.1:3690
  - sudo postconf -e milter_default_action=accept

