language: phyton

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix libmilter-dev libmilter1.0.1 sendemail
  # install dependencies
  - sudo pip install oletools
  - sudo pip install pymilter
  - sudo pip install configparser
  - sudo pip install olefile

before_script:
  - sudo service postfix stop
  - sudo postconf -e smtpd_milters=inet:127.0.0.1:3690
  - sudo postconf -e milter_default_action=accept
  - sudo service postfix start
  # install macromilter
  - sudo mkdir /etc/macromilter/
  - sudo mkdir -p /var/log/macromilter/
  - sudo cp ./macromilter/macromilter.py /usr/bin/
  - sudo cp ./travis/config.ini /etc/macromilter/
  - sudo cp ./travis/MacroMilter.conf /etc/init/
  - sudo init-checkconf /etc/init/MacroMilter.conf
  - sudo initctl log-priority debug
  - sudo initctl reload-configuration
  - sudo chown postfix:postfix -R /etc/macromilter
  - sudo chown postfix:postfix -R /var/log/macromilter
  - sudo chown postfix:postfix /usr/bin/macromilter.py
  - sudo chmod +x /usr/bin/macromilter.py
  - sudo cat /etc/init/MacroMilter.conf
  - sudo cat /etc/macromilter/config.ini
  #- sudo service MacroMilter start

script:
  - sudo python ./macromilter/macromilter.py
  - sudo tail -n 100 log.txt
  - sudo tail -n 100 /home/travis/macromilter.log
  - sudo tail -n 100 /home/travis/macromilter_upstart.log
  - sendemail -f travis@localhost -t travis@localhost -m "test" -s localhost -u "test" -a ./test_mails/Dok1.doc -v
  - sudo tail -n 100 /var/log/mail.log
  - sudo tail -n 400 /var/log/syslog
