language: phyton

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix libmilter-dev libmilter1.0.1 sendemail
  - sudo pip install oletools
  - sudo pip install pymilter
  - sudo pip install configparser

before_script:
  - sudo service postfix stop
  - sudo postconf -e smtpd_milters=inet:127.0.0.1:3690
  - sudo postconf -e milter_default_action=accept
  - sudo service postfix start
  - sudo mkdir /etc/macromilter/
  - sudo mkdir -p /var/log/macromilter/
  - sudo cp ./macromilter/macromilter.py /usr/bin/
  - sudo cp ./macromilter/config.ini /etc/macromilter/
  - sudo cp ./macromilter/MacroMilter.conf /etc/init/
  - sudo initctl reload-configuration
  - sudo chown postfix:postfix -R /etc/macromilter
  - sudo chown postfix:postfix -R /var/log/macromilter
  - sudo chown postfix:postfix /usr/bin/macromilter.py
  - sudo service MacroMilter start
  - sudo tail /var/log/macromilter/macromilter.log

script:
  - sendemail -f travis@localhost -t travis@localhost -m "test" -s localhost -u "test" -v
